apiVersion: v1
kind: Service
metadata:
  name: transaction-management-service
spec:
  selector:
    app: transaction-management
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8082
  type: ClusterIP
